### ISSUE TITLE
Zip Uncompress Stream Error when trying to install deno

### ISSUE THREAD

**Issue by eliassjogreen** [justjavac/dvm#7]
After i installed dvm yesterday and tried to install version 0.2.2 i got a `ZipUncompressStreamError` error.

First i ran the following command:
```
$ dvm install 0.2.2
```
but then got greeted by this lovely message:
```
  downloading [====================] 100% 0.0s
Extracting zip contents
Error extracting archive
{ ZipUncompressStreamError: end of central directory record signature not found
    at C:\Users\Elias\AppData\Roaming\npm\node_modules\dvm\node_modules\yauzl\index.js:187:14
    at C:\Users\Elias\AppData\Roaming\npm\node_modules\dvm\node_modules\yauzl\index.js:631:5
    at C:\Users\Elias\AppData\Roaming\npm\node_modules\dvm\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:458:17) name: 'ZipUncompressStreamError' }
deno v0.2.2 is not installed. Use `dvm install 0.2.2` to install it first.
```
(This is the debug info i got by running with `-d`:)
```
  dvm:info check whether the current version is installed +0ms
  dvm:info deno v0.2.2 is not installed +3ms
  dvm:info try to download... 0.2.2 +0ms
  dvm:info using mirror denocn +1ms
  dvm:info using registry http://cdn.devtips.cn/deno/releases/download/ +0ms
  dvm:info remote package url: http://cdn.devtips.cn/deno/releases/download//v0.2.2/deno_win_x64.zip +0ms
  dvm:info file will save at C:\Users\Elias\AppData\Local\Temp\deno_win_x64.zip +2ms
  dvm:info file already exists, try to delete it... +1ms
  dvm:info delete successfully +0ms
  dvm:info start downloading +1ms
  downloading [====================] 100% 0.0s
  dvm:info download finish +7s
  dvm:info successfully downloaded files to local files +2ms
  dvm:info rename C:\Users\Elias\AppData\Local\Temp\deno_win_x64.zip-download-1544537685133 to C:\Users\Elias\AppData\Local\Temp\deno_win_x64.zip +1ms
Extracting zip contents
Error extracting archive
{ ZipUncompressStreamError: end of central directory record signature not found
    at C:\Users\Elias\AppData\Roaming\npm\node_modules\dvm\node_modules\yauzl\index.js:187:14
    at C:\Users\Elias\AppData\Roaming\npm\node_modules\dvm\node_modules\yauzl\index.js:631:5
    at C:\Users\Elias\AppData\Roaming\npm\node_modules\dvm\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:458:17) name: 'ZipUncompressStreamError' }
  dvm:info deno location: C:\Users\Elias\.dvm\0.2.2\deno.exe +18ms
deno v0.2.2 is not installed. Use `dvm install 0.2.2` to install it first.
```

### Versions

I am using Windows 10 Home, ran the command in powershell and using dvm version 0.1.7.

**Comment by justjavac** [comment]
fixed. Rewrite using rust
